### ISSUE TITLE
Links in chapter 0 don't work.

### ISSUE THREAD

**Issue by das-g** [arialdomartini/stairway-to-emacs#1]
The links here
https://github.com/arialdomartini/stairway-to-emacs/blob/55c1fe3cb8ab6a899183e066c14f702e60494925/000-intro.org?plain=1#L39
don't work for me, neither [in the GitHub preview](https://github.com/arialdomartini/stairway-to-emacs/blob/55c1fe3cb8ab6a899183e066c14f702e60494925/000-intro.org#how), nor in my (yet unconfigured) Emacs itself.
- On the GitHub web interface they link to https://github.com/arialdomartini/stairway-to-emacs/blob/master/doom and  https://github.com/arialdomartini/stairway-to-emacs/blob/master/spacemacs.
- In `emacs-gtk` I get a model "No match - create this as a new heading?" window when clicking one of those two links:
  ![image](https://github.com/user-attachments/assets/536b8280-23e0-44c9-baca-aaefa60900d1)
  ![image](https://github.com/user-attachments/assets/dfc0f602-80f7-4f83-980b-88c7912f5593)
- In `emacs-nox`, `emacs -nw` and `emacs-gtk -nw`, when placing the "point" (text cursor) on one of those links an hitting C-c C-o (or executing `open-link-at-point`) I'm getting `No match - create this as a new heading? (yes or no)`
  ![image](https://github.com/user-attachments/assets/e71ca013-e568-49e7-a275-a3e8cfe7697b)

Maybe some special configuration is needed for
https://github.com/arialdomartini/stairway-to-emacs/blob/55c1fe3cb8ab6a899183e066c14f702e60494925/000-intro.org?plain=1#L44-L45
to take effect? If so, this tutorial shouldn't depend on it, as most won't have a such-configured Emacs when they begin the tutorial.

**Comment by das-g** [comment]
The links in Chapters 2 & 3 are also affected.

**Comment by arialdomartini** [comment]
Yes! I am still new on org and I did not know I had to use `LINK`, not `TARGET`.
As you suspected, the problem was exactly in

https://github.com/arialdomartini/stairway-to-emacs/blob/55c1fe3cb8ab6a899183e066c14f702e60494925/000-intro.org?plain=1#L44-L45
