### ISSUE TITLE
"Canc" key?

### ISSUE THREAD

**Issue by das-g** [arialdomartini/stairway-to-emacs#2]
https://github.com/arialdomartini/stairway-to-emacs/blob/55c1fe3cb8ab6a899183e066c14f702e60494925/001-m-x-c-g.org?plain=1#L50

What's the "Canc" key? Do you mean [<kbd>← Backspace</kbd>](https://en.wikipedia.org/wiki/Backspace)?

**Comment by arialdomartini** [comment]
Yes! My bad, I instinctively used the name on Italian keyboards.
