### ISSUE TITLE
Prefer lowercase letters for indicating single-letter keys.

### ISSUE THREAD

**Issue by das-g** [arialdomartini/stairway-to-emacs#3]
https://github.com/arialdomartini/stairway-to-emacs/blob/55c1fe3cb8ab6a899183e066c14f702e60494925/001-m-x-c-g.org?plain=1#L9-L10

As the "X" and "G" are shown in uppercase here, some might misinterpret these as:
* hold <kbd>Alt</kbd> **and hold <kbd>Shift</kbd>** while hitting <kbd>x</kbd>
  * or, alternatively, **activate caps lock**, before holding <kbd>Alt</kbd> while hitting <kbd>x</kbd>
* hold <kbd>Ctrl</kbd> **and hold <kbd>Shift</kbd>** while hitting <kbd>g</kbd>
  * or, alternatively, **activate caps lock**, before holding <kbd>Alt</kbd> while hitting <kbd>g</kbd>

(I know the labels on the physical keyboard are typically in upper case. Still, lowercase will IMHO be less ambiguous in instructions when <kbd>Shift</kbd> or caps lock should not be used.)

**Comment by arialdomartini** [comment]
Makes sense. Thank you.
